In [10]:
import pandas as pd
import understatapi
import numpy as np

client = understatapi.UnderstatClient()

years = ["2021", "2022", "2023", "2024"]

seasons = []

for y in years:
    season_data = client.league("EPL").get_team_data(season = y)
    seasons.append(season_data)

season_dfs = []
for s in seasons:
    rows = []
    for team_id, team_data in s.items():
        team_name = team_data["title"]

        for match in team_data["history"]:
            row = match.copy()
            row["team"] = team_name
            row["team_id"] = team_id
            rows.append(row)
    df = pd.DataFrame(rows)
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values(["team", "date"])
    df = df.set_index(["team", "date"])



    season_dfs.append(df)
for l in season_dfs:
    display(l.head(2))

                            h_a        xG      xGA      npxG    npxGA  \
team    date
Arsenal 2021-08-13 19:00:00   a  1.023850  1.88818  1.023850  1.88818
        2021-08-22 15:30:00   h  0.630099  3.64132  0.630099  3.64132

                                                ppda             ppda_allowed  \
team    date
Arsenal 2021-08-13 19:00:00  {'att': 127, 'def': 22}  {'att': 290, 'def': 18}
        2021-08-22 15:30:00  {'att': 376, 'def': 23}  {'att': 156, 'def': 15}

                             deep  deep_allowed  scored  missed    xpts  \
team    date
Arsenal 2021-08-13 19:00:00    10             7       0       2  0.6559
        2021-08-22 15:30:00     3            19       0       2  0.0659

                            result  wins  draws  loses  pts     npxGD team_id
team    date
Arsenal 2021-08-13 19:00:00      l     0      0      1    0 -0.864330      83
        2021-08-22 15:30:00      l     0      0      1    0 -3.011221      83

                            h_a       xG       xGA     npxG     npxGA  \
team    date
Arsenal 2022-08-05 19:00:00   a  1.43601  1.206370  1.43601  1.206370
        2022-08-13 14:00:00   h  3.01070  0.690679  3.01070  0.690679

                                                ppda             ppda_allowed  \
team    date
Arsenal 2022-08-05 19:00:00  {'att': 355, 'def': 28}  {'att': 246, 'def': 24}
        2022-08-13 14:00:00  {'att': 279, 'def': 27}  {'att': 196, 'def': 14}

                             deep  deep_allowed  scored  missed    xpts  \
team    date
Arsenal 2022-08-05 19:00:00    13             8       2       0  1.5584
        2022-08-13 14:00:00    10             5       4       2  2.7487

                            result  wins  draws  loses  pts     npxGD team_id
team    date
Arsenal 2022-08-05 19:00:00      w     1      0      0    3  0.229640      83
        2022-08-13 14:00:00      w     1      0      0    3  2.320021      83

                            h_a       xG       xGA     npxG     npxGA  \
team    date
Arsenal 2023-08-12 11:30:00   h  0.84262  0.966305  0.84262  0.966305
        2023-08-21 19:00:00   a  2.20593  1.069160  1.44480  1.069160

                                                ppda             ppda_allowed  \
team    date
Arsenal 2023-08-12 11:30:00  {'att': 108, 'def': 27}  {'att': 441, 'def': 10}
        2023-08-21 19:00:00  {'att': 192, 'def': 20}  {'att': 230, 'def': 16}

                             deep  deep_allowed  scored  missed    xpts  \
team    date
Arsenal 2023-08-12 11:30:00     9             4       2       1  1.1754
        2023-08-21 19:00:00     7            10       1       0  2.2217

                            result  wins  draws  loses  pts     npxGD team_id
team    date
Arsenal 2023-08-12 11:30:00      w     1      0      0    3 -0.123685      83
        2023-08-21 19:00:00      w     1      0      0    3  0.375640      83

                            h_a       xG       xGA     npxG     npxGA  \
team    date
Arsenal 2024-08-17 14:00:00   h  1.62830  0.575835  1.62830  0.575835
        2024-08-24 16:30:00   a  1.41399  1.316640  1.41399  1.316640

                                                ppda             ppda_allowed  \
team    date
Arsenal 2024-08-17 14:00:00  {'att': 202, 'def': 26}  {'att': 238, 'def': 22}
        2024-08-24 16:30:00  {'att': 175, 'def': 30}  {'att': 311, 'def': 18}

                             deep  deep_allowed  scored  missed    xpts  \
team    date
Arsenal 2024-08-17 14:00:00    14             2       2       0  2.1894
        2024-08-24 16:30:00    10             3       2       0  1.4615

                            result  wins  draws  loses  pts     npxGD team_id
team    date
Arsenal 2024-08-17 14:00:00      w     1      0      0    3  1.052465      83
        2024-08-24 16:30:00      w     1      0      0    3  0.097350      83

In [22]:
s21 = pd.read_csv("2025.csv")


team_map = {
    "Man City": "Manchester City",
    "Man United": "Manchester United",
    "Nott'm Forest": "Nottingham Forest",
    "Newcastle": "Newcastle United",
    "Wolves": "Wolverhampton Wanderers"
}

s21.head(9)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99

In [6]:
eps = 1 * 10**-6
eps

1e-06

In [11]:
print(season_dfs[0]["team"].unique())

KeyError: 'team'

In [24]:
game_results = []
keep_cols = ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR"]
for y in years:
    df = pd.read_csv(f'{y}.csv')[keep_cols]
    df["HomeTeam"] = df["HomeTeam"].replace(team_map)
    df = df.apply(pd.to_numeric, errors="ignore")
   # make label: 1 = home win, 0 = draw, -1 = away win
    df["FTR"] = np.select(
        [df["FTHG"] > df["FTAG"], df["FTHG"] == df["FTAG"]],
        [1, 0],
        default=-1
    )
    game_results.append(df)

game_results[0].head()

/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_1227/1360529187.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_1227/1360529187.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_1227/1360529187.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_1227/1360529187.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

         Date           HomeTeam        AwayTeam  FTHG  FTAG  FTR
0  13/08/2021          Brentford         Arsenal     2     0    1
1  14/08/2021  Manchester United           Leeds     5     1    1
2  14/08/2021            Burnley        Brighton     1     2   -1
3  14/08/2021            Chelsea  Crystal Palace     3     0    1
4  14/08/2021            Everton     Southampton     3     1    1

In [1]:
import pandas as pd
import understatapi
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, log_loss, classification_report, confusion_matrix

client = understatapi.UnderstatClient()

class Footy_Predictor:
    def __init__(self, roll_n = 5, min_n = 1):
        self.roll_n = roll_n
        self.min_n = min_n
        self.eps = 1 * 10**(-6)
        self.team_map = {
            "Man City": "Manchester City",
            "Man United": "Manchester United",
            "Nott'm Forest": "Nottingham Forest",
            "Newcastle": "Newcastle United",
            "Wolves": "Wolverhampton Wanderers"
        }




        years = ["2021", "2022", "2023", "2024", "2025"]

        seasons = []

        for y in years:
            season_data = client.league("EPL").get_team_data(season = y)
            seasons.append(season_data)

        season_dfs = []
        for s in seasons:
            rows = []
            for team_id, team_data in s.items():
                team_name = team_data["title"]

                for match in team_data["history"]:
                    row = match.copy()
                    row["team"] = team_name
                    row["team_id"] = team_id
                    rows.append(row)
            df = pd.DataFrame(rows)
            df["date"] = pd.to_datetime(df["date"]).dt.date
            df = df.sort_values(["team", "date"])
            df = df.set_index(["team", "date"])

            #new columns
            df['deep_ratio'] = round(df['deep'] / (df['deep'] + df['deep_allowed'] + self.eps),2)


            df = self.extract_ppda(df, col = "ppda", prefix = "ppda")
            df = self.extract_ppda(df, col = "ppda_allowed", prefix = "ppda_allowed")
            

            season_dfs.append(df)

        #the columns we're going to engineer new features on
        mean_metrics = ["xG", "xGA", "npxGD", "npxG", "npxGA", "xpts", "deep_ratio"]

        #the columns I'll want to keep (to later train our model on)
        self.key_stats = [
        'ppda_att', 'ppda_def', 'ppda_allowed_att', 'ppda_allowed_def',
        'rolling_xG_5', 'rolling_xGA_5', 'rolling_npxGD_5', 'rolling_npxG_5', 
        'rolling_npxGA_5', 'rolling_xpts_5', 'rolling_deep_ratio_5', 'rolling_xG_std_5', 
        'rolling_xGA_std_5', 'rolling_npxGD_std_5'
        ]
        for i, s in enumerate(season_dfs):
            for m_col in mean_metrics:
                s = self.rolling_mean(s, m_col)

            for sd_col in ["xG", "xGA", "npxGD"]:
                s = self.rolling_std(s, sd_col)
            s = s.reset_index()[["team", "date"] + self.key_stats]
            s_clean = s.set_index(["team", "date"])
            s_clean = s_clean.dropna()
            

            season_dfs[i] = s_clean
        self.seasons = dict(zip(years, season_dfs))


        game_results = []
        keep_cols = ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR"]
        for y in years:
            df = pd.read_csv(f'{y}.csv')[keep_cols]

            #changing all the team names to match our understat team names
            df["HomeTeam"] = df["HomeTeam"].replace(self.team_map)
            df = df.apply(pd.to_numeric, errors="ignore")
            # make label: 1 = home win, 0 = draw, -1 = away win
            df["FTR"] = np.select(
                [df["FTHG"] > df["FTAG"], df["FTHG"] == df["FTAG"]],
                [1, 0],
                default=-1
            )
            drop_cols = ["FTHG", "FTAG"]
            df = df.drop(columns = drop_cols)
            #change our dates to the proper format
            df["Date"] = pd.to_datetime(df["Date"], dayfirst= True, errors = "raise").dt.date
            df = df.sort_values("Date")


            #drop Arsenals first game so that our results dataframes align with our stats dataframes
            first_game_mask = ((df["HomeTeam"] == "Arsenal") | (df["AwayTeam"] == "Arsenal"))
            first_ars_index = df.loc[first_game_mask].index[:2]
            df = df.drop(index = first_ars_index)

            game_results.append(df)
        self.results = dict(zip(years, game_results))


    

    """ 
    Now it's time to build the methods that we'll use to clean our dfs, 
    engineer new features, merging our dataframes,
    and train some models based on these newfeatures
    """


    def extract_ppda(self, df, col, prefix):
        """
        Extract att/def from Understat PPDA dict column
        and compute the PPDA ratio.
        """
        df[f"{prefix}_att"] = df[col].apply(
            lambda x: x.get("att") if isinstance(x, dict) else np.nan
        )
        df[f"{prefix}_def"] = df[col].apply(
            lambda x: x.get("def") if isinstance(x, dict) else np.nan
        )

        df[prefix] = df[f"{prefix}_att"] / (df[f"{prefix}_def"]+ self.eps)
        return df 


    def rolling_mean(self, df, col):
        """
        A function used to get the rolling mean of a column over a number n amount of games 
        """
        out_col = f'rolling_{col}_{self.roll_n}'
        df[out_col] = (
            df.groupby("team")[f'{col}'].shift(1)
            .rolling(window = self.roll_n, min_periods = self.min_n).mean()
        )

        return df
    
    def rolling_std(self, df, col):
        """
        A function used to get the rolling mean of a column over a number n amount of games 
        """

        out_col = f'rolling_{col}_std_{self.roll_n}'
        df[out_col] = (
            df.groupby("team")[f'{col}'].shift(1)
            .rolling(window = self.roll_n, min_periods = self.min_n).std()
        )
        return df




    def build_match_df(self, year):

        """ 
        Merging our dataframes in order to have a match ready dataframe that we can use our 
        engineered features to train a model and make predictions
        """
        stats = self.seasons[year].reset_index()
        results = self.results[year].copy()

        home = stats.rename(columns={c: f"home_{c}" for c in self.key_stats})
        away = stats.rename(columns={c: f"away_{c}" for c in self.key_stats})

        df = (
            results.merge(
                home, 
                left_on = ["HomeTeam", "Date"],
                right_on = ["team", "date"],
                how = "inner"
            ).merge(
                away,
                left_on = ["AwayTeam", "Date"], 
                right_on = ["team", "date"],
                how = "inner"
            )
        )

        return df.drop(columns = ["team_x", "date_x", "team_y", "date_y"])



    def train_model(self):
        #building the merged dataframes that we'll use to train
        df_2021 = self.build_match_df("2021")
        df_2022 = self.build_match_df("2022")
        df_2023 = self.build_match_df("2023")
        df_2024 = self.build_match_df("2024")
        df_2025 = self.build_match_df("2025")


        #set a cutoff data that we can use to split how far into this season we'll train our model on
        cutoff_date = df_2025["Date"].quantile(0.5)

        df_25_train = df_2025[df_2025["Date"] <= cutoff_date]
        df_25_test = df_2025[df_2025["Date"] > cutoff_date]


        #combine all of our training dataframes
        train_df = pd.concat([df_2021, df_2022, df_2023, df_2024, df_25_train], ignore_index= True)

        drop_cols = ["FTR", "Date", "HomeTeam", "AwayTeam"]

        #make all of our training columns numerical and set our target column that we will predict on
        X_train = train_df.drop(columns= drop_cols)
        y_train = train_df["FTR"]

        X_test = df_25_test.drop(columns= drop_cols)
        y_test = df_25_test["FTR"]

        #create a lable map since we're using XGBoost
        lab_map = {-1:0, 0:1, 1:2}
        y_train = y_train.map(lab_map)
        y_test = y_test.map(lab_map)

        model = XGBClassifier(
            objective= "multi:softprob",
            num_class =3,
            n_estimators = 500,
            max_depth = 5,
            learning_rate = 0.03,
            subsample = 0.9,
            colsample_bytree = 0.9,
            eval_metric = "mlogloss",
            random_state = 42
        )

        model.fit(X_train, y_train)


        preds = model.predict(X_test)
        probs = model.predict_proba(X_test)

        acc = accuracy_score(y_test, preds)
        ll = log_loss(y_test, probs)

        print("Accuracy:", acc)
        print("Log loss:", ll)
        print("\nClassification report:\n", classification_report(y_test, preds))
        print("\nConfusion matrix:\n", confusion_matrix(y_test, preds))

        # store stuff on self so you can reuse later
        self.model = model
        self.cutoff_date_2025 = cutoff_date

        # return if you want to use outside the class
        return model, {"accuracy": acc, "log_loss": ll}

In [2]:
foot = Footy_Predictor()

/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/382537978.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/382537978.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/382537978.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/382537978.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/382537978.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

In [5]:
yes = foot.seasons["2021"]
yes.tail()

                                    ppda_att  ppda_def  ppda_allowed_att  \
team                    date
Wolverhampton Wanderers 2022-04-30       268        16               284
                        2022-05-07       293        16               212
                        2022-05-11       543        15               259
                        2022-05-15       202        15               291
                        2022-05-22       367        11               257

                                    ppda_allowed_def  rolling_xG_5  \
team                    date
Wolverhampton Wanderers 2022-04-30                23      0.894833
                        2022-05-07                22      0.857588
                        2022-05-11                28      0.946278
                        2022-05-15                13      0.704348
                        2022-05-22                25      0.842787

                                    rolling_xGA_5  rolling_npxGD_5  \
team                    date
Wolverhampton Wanderers 2022-04-30       1.568524        -0.369223
                        2022-05-07       2.070428        -0.603906
                        2022-05-11       1.870418        -0.162972
                        2022-05-15       2.166514        -0.853233
                        2022-05-22       2.185182        -0.885695

                                    rolling_npxG_5  rolling_npxGA_5  \
team                    date
Wolverhampton Wanderers 2022-04-30        0.894833         1.264056
                        2022-05-07        0.857588         1.461494
                        2022-05-11        0.946278         1.109250
                        2022-05-15        0.704348         1.557580
                        2022-05-22        0.842787         1.728482

                                    rolling_xpts_5  rolling_deep_ratio_5  \
team                    date
Wolverhampton Wanderers 2022-04-30         0.84258                 0.448
                        2022-05-07         0.54698                 0.452
                        2022-05-11         0.71152                 0.384
                        2022-05-15         0.49718                 0.382
                        2022-05-22         0.61358                 0.548

                                    rolling_xG_std_5  rolling_xGA_std_5  \
team                    date
Wolverhampton Wanderers 2022-04-30          0.528669           0.889263
                        2022-05-07          0.550852           0.762025
                        2022-05-11          0.654006           0.636697
                        2022-05-15          0.558550           0.935383
                        2022-05-22          0.519844           0.917998

                                    rolling_npxGD_std_5
team                    date
Wolverhampton Wanderers 2022-04-30             0.827008
                        2022-05-07             0.746968
                        2022-05-11             0.673635
                        2022-05-15             1.320449
                        2022-05-22             1.307555

In [45]:
no = foot.results["2021"]
no.head()

        Date           HomeTeam        AwayTeam  FTHG  FTAG  FTR
1 2021-08-14  Manchester United           Leeds     5     1    1
2 2021-08-14            Burnley        Brighton     1     2   -1
3 2021-08-14            Chelsea  Crystal Palace     3     0    1
4 2021-08-14            Everton     Southampton     3     1    1
5 2021-08-14          Leicester          Wolves     1     0    1

In [3]:
ma = foot.build_match_df("2021")
ma

,Date,HomeTeam,AwayTeam,FTR,home_ppda_att,home_ppda_def,home_ppda_allowed_att,home_ppda_allowed_def,home_rolling_xG_5,home_rolling_xGA_5,...,away_rolling_xG_5,away_rolling_xGA_5,away_rolling_npxGD_5,away_rolling_npxG_5,away_rolling_npxGA_5,away_rolling_xpts_5,away_rolling_deep_ratio_5,away_rolling_xG_std_5,away_rolling_xGA_std_5,away_rolling_npxGD_std_5
0,2021-08-14,Manchester United,Leeds,1,277,22,239,33,3.152678,0.862959,...,1.469398,1.281397,-0.002292,1.279105,1.281396,1.493900,0.4875,0.889647,0.713488,0.571478
1,2021-08-14,Burnley,Brighton,-1,322,18,119,15,2.466390,1.151553,...,1.873804,1.510832,0.743557,1.873804,1.130247,1.508300,0.5900,1.291951,0.961319,1.396806
2,2021-08-14,Chelsea,Crystal Palace,1,277,42,355,5,1.235390,1.497299,...,1.530220,0.835727,0.504201,1.339928,0.835727,1.926025,0.8650,0.256931,0.717000,0.967977
3,2021-08-14,Everton,Southampton,1,158,23,151,27,1.560007,0.629557,...,0.970736,2.285127,-1.124099,0.970736,2.094834,0.649925,0.2300,0.515257,0.945950,1.132775
4,2021-08-14,Watford,Aston Villa,1,303,21,182,28,2.113931,0.584892,...,1.141791,1.564243,-0.232159,1.141791,1.373950,1.241925,0.5150,1.083414,1.349933,1.893127
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,2022-05-22,Manchester City,Aston Villa,1,124,17,282,12,3.258142,0.775631,...,1.473517,1.287584,0.338167,1.473517,1.135351,1.402280,0.4860,0.612489,0.552652,0.997496
298,2022-05-22,Brighton,West Ham,1,242,14,233,14,1.996583,1.226930,...,1.580088,1.624341,0.260215,1.427854,1.167639,1.310680,0.4460,1.351335,0.709834,1.346626
299,2022-05-22,Brentford,Leeds,-1,206,21,262,20,1.923957,1.509428,...,0.965904,2.216216,-1.250312,0.965904,2.216216,0.577560,0.2260,0.745780,0.673411,0.819288
300,2022-05-22,Arsenal,Everton,1,96,20,298,6,1.421779,1.659882,...,1.398942,1.267399,-0.020691,1.246708,1.267399,1.447480,0.4520,0.786399,0.618691,0.496621
301,2022-05-22,Norwich,Tottenham,-1,403,24,239,14,0.908121,2.203217,...,1.794696,0.730973,0.759255,1.490228,0.730973,1.995980,0.5900,1.154161,0.441288,1.209354

In [56]:
ma["FTR"].value_counts(normalize = True)

FTR
 1    0.447020
-1    0.314570
 0    0.238411
Name: proportion, dtype: float64

In [57]:
ma.isna().sum()

Date                         0
HomeTeam                     0
AwayTeam                     0
FTHG                         0
FTAG                         0
FTR                          0
home_ppda_att                0
home_ppda_def                0
home_ppda_allowed_att        0
home_ppda_allowed_def        0
home_rolling_xG_5            0
home_rolling_xGA_5           0
home_rolling_npxGD_5         0
home_rolling_npxG_5          0
home_rolling_npxGA_5         0
home_rolling_xpts_5          0
home_rolling_deep_ratio_5    0
home_rolling_xG_std_5        0
home_rolling_xGA_std_5       0
home_rolling_npxGD_std_5     0
away_ppda_att                0
away_ppda_def                0
away_ppda_allowed_att        0
away_ppda_allowed_def        0
away_rolling_xG_5            0
away_rolling_xGA_5           0
away_rolling_npxGD_5         0
away_rolling_npxG_5          0
away_rolling_npxGA_5         0
away_rolling_xpts_5          0
away_rolling_deep_ratio_5    0
away_rolling_xG_std_5        0
away_rolling_xGA_std_5       0
away_rolling_npxGD_std_5     0
dtype: int64

In [ ]:
key_stats = [
    'ppda_att', 'ppda_def', 'ppda_allowed_att', 'ppda_allowed_def',
      'rolling_xG_5', 'rolling_xGA_5', 'rolling_npxGD_5', 'rolling_npxG_5', 
      'rolling_npxGA_5', 'rolling_xpts_5', 'rolling_deep_ratio_5', 'rolling_xG_std_5', 
      'rolling_xGA_std_5', 'rolling_npxGD_std_5'
      ]

In [4]:
yes = foot.train_model()

Accuracy: 0.5066666666666667
Log loss: 1.0844245679698408

Classification report:
               precision    recall  f1-score   support

           0       0.48      0.55      0.51        22
           1       0.56      0.35      0.43        26
           2       0.50      0.63      0.56        27

    accuracy                           0.51        75
   macro avg       0.51      0.51      0.50        75
weighted avg       0.52      0.51      0.50        75


Confusion matrix:
 [[12  4  6]
 [ 6  9 11]
 [ 7  3 17]]

In [32]:
import pandas as pd
import understatapi
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, log_loss, classification_report, confusion_matrix

client = understatapi.UnderstatClient()

class Footy_Predictor:
    def __init__(self, roll_n = 5, min_n = 1):
        self.roll_n = roll_n
        self.min_n = min_n
        self.eps = 1 * 10**(-6)
        self.team_map = {
            "Man City": "Manchester City",
            "Man United": "Manchester United",
            "Nott'm Forest": "Nottingham Forest",
            "Newcastle": "Newcastle United",
            "Wolves": "Wolverhampton Wanderers"
        }




        years = ["2021", "2022", "2023", "2024", "2025"]

        seasons = []

        for y in years:
            season_data = client.league("EPL").get_team_data(season = y)
            seasons.append(season_data)

        season_dfs = []
        for s in seasons:
            rows = []
            for team_id, team_data in s.items():
                team_name = team_data["title"]

                for match in team_data["history"]:
                    row = match.copy()
                    row["team"] = team_name
                    row["team_id"] = team_id
                    rows.append(row)
            df = pd.DataFrame(rows)
            df["date"] = pd.to_datetime(df["date"]).dt.date
            df = df.sort_values(["team", "date"])
            df = df.set_index(["team", "date"])

            #new columns
            df['deep_ratio'] = round(df['deep'] / (df['deep'] + df['deep_allowed'] + self.eps),2)


            df = self.extract_ppda(df, col = "ppda", prefix = "ppda")
            df = self.extract_ppda(df, col = "ppda_allowed", prefix = "ppda_allowed")
            

            season_dfs.append(df)

        #the columns we're going to engineer new features on
        mean_metrics = ["xG", "xGA", "npxGD", "npxG", "npxGA", "xpts", "deep_ratio"]

        #the columns I'll want to keep (to later train our model on)
        self.key_stats = [
        'ppda_att', 'ppda_def', 'ppda_allowed_att', 'ppda_allowed_def',
        'rolling_xG_5', 'rolling_xGA_5', 'rolling_npxGD_5', 'rolling_npxG_5', 
        'rolling_npxGA_5', 'rolling_xpts_5', 'rolling_deep_ratio_5', 'rolling_xG_std_5', 
        'rolling_xGA_std_5', 'rolling_npxGD_std_5'
        ]
        for i, s in enumerate(season_dfs):
            for m_col in mean_metrics:
                s = self.rolling_mean(s, m_col)

            for sd_col in ["xG", "xGA", "npxGD"]:
                s = self.rolling_std(s, sd_col)
            s = s.reset_index()[["team", "date"] + self.key_stats]
            s_clean = s.set_index(["team", "date"])
            s_clean = s_clean.dropna()
            

            season_dfs[i] = s_clean
        self.seasons = dict(zip(years, season_dfs))


        game_results = []
        keep_cols = ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR"]
        for y in years:
            df = pd.read_csv(f'{y}.csv')[keep_cols]

            #changing all the team names to match our understat team names
            df["HomeTeam"] = df["HomeTeam"].replace(self.team_map)
            df = df.apply(pd.to_numeric, errors="ignore")
            # make label: 1 = home win, 0 = draw, -1 = away win
            df["FTR"] = np.select(
                [df["FTHG"] > df["FTAG"], df["FTHG"] == df["FTAG"]],
                [1, 0],
                default=-1
            )
            drop_cols = ["FTHG", "FTAG"]
            df = df.drop(columns = drop_cols)
            #change our dates to the proper format
            df["Date"] = pd.to_datetime(df["Date"], dayfirst= True, errors = "raise").dt.date
            df = df.sort_values("Date")


            #drop Arsenals first game so that our results dataframes align with our stats dataframes
            first_game_mask = ((df["HomeTeam"] == "Arsenal") | (df["AwayTeam"] == "Arsenal"))
            first_ars_index = df.loc[first_game_mask].index[:2]
            df = df.drop(index = first_ars_index)

            game_results.append(df)
        self.results = dict(zip(years, game_results))


    

    """ 
    Now it's time to build the methods that we'll use to clean our dfs, 
    engineer new features, merging our dataframes,
    and train some models based on these newfeatures
    """


    def extract_ppda(self, df, col, prefix):
        """
        Extract att/def from Understat PPDA dict column
        and compute the PPDA ratio.
        """
        df[f"{prefix}_att"] = df[col].apply(
            lambda x: x.get("att") if isinstance(x, dict) else np.nan
        )
        df[f"{prefix}_def"] = df[col].apply(
            lambda x: x.get("def") if isinstance(x, dict) else np.nan
        )

        df[prefix] = df[f"{prefix}_att"] / (df[f"{prefix}_def"]+ self.eps)
        return df 


    def rolling_mean(self, df, col):
        """
        A function used to get the rolling mean of a column over a number n amount of games 
        """
        out_col = f'rolling_{col}_{self.roll_n}'
        df[out_col] = (
            df.groupby("team")[f'{col}'].shift(1)
            .rolling(window = self.roll_n, min_periods = self.min_n).mean()
        )

        return df
    
    def rolling_std(self, df, col):
        """
        A function used to get the rolling mean of a column over a number n amount of games 
        """

        out_col = f'rolling_{col}_std_{self.roll_n}'
        df[out_col] = (
            df.groupby("team")[f'{col}'].shift(1)
            .rolling(window = self.roll_n, min_periods = self.min_n).std()
        )
        return df




    def build_match_df(self, year):

        """ 
        Merging our dataframes in order to have a match ready dataframe that we can use our 
        engineered features to train a model and make predictions
        """
        stats = self.seasons[year].reset_index()
        results = self.results[year].copy()

        home = stats.rename(columns={c: f"home_{c}" for c in self.key_stats})
        away = stats.rename(columns={c: f"away_{c}" for c in self.key_stats})

        df = (
            results.merge(
                home, 
                left_on = ["HomeTeam", "Date"],
                right_on = ["team", "date"],
                how = "inner"
            ).merge(
                away,
                left_on = ["AwayTeam", "Date"], 
                right_on = ["team", "date"],
                how = "inner"
            )
        )

        return df.drop(columns = ["team_x", "date_x", "team_y", "date_y"])



    def train_model(self):
        #building the merged dataframes that we'll use to train
        df_2021 = self.build_match_df("2021")
        df_2022 = self.build_match_df("2022")
        df_2023 = self.build_match_df("2023")
        df_2024 = self.build_match_df("2024")
        df_2025 = self.build_match_df("2025")


        #set a cutoff data that we can use to split how far into this season we'll train our model on
        cutoff_date = df_2025["Date"].quantile(0.5)

        df_25_train = df_2025[df_2025["Date"] <= cutoff_date]
        df_25_test = df_2025[df_2025["Date"] > cutoff_date]


        #combine all of our training dataframes
        train_df = pd.concat([df_2021, df_2022, df_2023, df_2024, df_25_train], ignore_index= True)

        drop_cols = ["FTR", "Date", "HomeTeam", "AwayTeam"]

        #make all of our training columns numerical and set our target column that we will predict on
        X_train = train_df.drop(columns= drop_cols)
        y_train = train_df["FTR"]

        X_test = df_25_test.drop(columns= drop_cols)
        y_test = df_25_test["FTR"]

        #create a lable map since we're using XGBoost
        lab_map = {-1:0, 0:1, 1:2}
        y_train = y_train.map(lab_map)
        y_test = y_test.map(lab_map)

        model = XGBClassifier(
            objective= "multi:softprob",
            num_class =3,
            n_estimators = 500,
            max_depth = 5,
            learning_rate = 0.03,
            subsample = 0.9,
            colsample_bytree = 0.9,
            eval_metric = "mlogloss",
            random_state = 42
        )

        model.fit(X_train, y_train)


        preds = model.predict(X_test)
        probs = model.predict_proba(X_test)

        acc = accuracy_score(y_test, preds)
        ll = log_loss(y_test, probs)

        print("Accuracy:", acc)
        print("Log loss:", ll)
        print("\nClassification report:\n", classification_report(y_test, preds))
        print("\nConfusion matrix:\n", confusion_matrix(y_test, preds))

        # store stuff on self so you can reuse later
        self.model = model
        self.cutoff_date_2025 = cutoff_date

        # return if you want to use outside the class
        return self.model
    
    def get_stats(self, team, date, year):
        stats_df = self.seasons[year]
        stats_df.index = stats_df.index.set_levels(
            pd.to_datetime(stats_df.index.levels[1]),
            level='date')

        cutoff = pd.to_datetime(date)

        team_df = (
            stats_df
            .xs(team, level="team")
            .sort_index()
        )

        team_stats = team_df.loc[:cutoff]

        if team_stats.empty:
            raise ValueError(f"No stats available for {team} before {cutoff}")

        return team_stats.iloc[-1]


    def predict_game(self, home_team, away_team, date, year):
        if not hasattr(self, "model"):
            raise ValueError("Model not trained. Call train_model() first.")

        # get pre-match stats
        home_stats = self.get_stats(home_team, date, year)
        away_stats = self.get_stats(away_team, date, year)

        # build feature row
        row = pd.concat([
            home_stats.add_prefix("home_"),
            away_stats.add_prefix("away_")
        ])

        # drop non-feature columns (safety)
        drop_cols = ["FTR", "Date", "HomeTeam", "AwayTeam"]
        row = row.drop([c for c in drop_cols if c in row.index])

        X = row.to_frame().T

        # predict
        pred = self.model.predict(X)[0]
        probs = self.model.predict_proba(X)[0]

        inv_map = {0: -1, 1: 0, 2: 1}
        result = inv_map[pred]

        return {
            "prediction": result,
            "home_win_prob": f"{round(float(probs[2]) * 100,2)}%",
            "draw_prob": f"{round(float(probs[1]) * 100, 2)}%",
            "away_win_prob": f"{round(float(probs[0]) * 100, 2)}%"
        }

In [34]:

foot = Footy_Predictor()
foot.train_model()

result = foot.predict_game("Arsenal", "Manchester United", date = "2026-01-25", year = "2025")
print(result)

/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/935344868.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/935344868.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/935344868.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/935344868.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")
/var/folders/4j/8ccbsmy55bs6gr7lw4mgm7sh0000gn/T/ipykernel_55876/935344868.py:91: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

Accuracy: 0.5333333333333333
Log loss: 1.084883873508262

Classification report:
               precision    recall  f1-score   support

           0       0.54      0.64      0.58        22
           1       0.62      0.31      0.41        26
           2       0.50      0.67      0.57        27

    accuracy                           0.53        75
   macro avg       0.55      0.54      0.52        75
weighted avg       0.55      0.53      0.52        75


Confusion matrix:
 [[14  2  6]
 [ 6  8 12]
 [ 6  3 18]]
{'prediction': 1, 'home_win_prob': '46.07%', 'draw_prob': '44.23%', 'away_win_prob': '9.7%'}

In [17]:
foot.build_match_df("2025").head()

,Date,HomeTeam,AwayTeam,FTR,home_ppda_att,home_ppda_def,home_ppda_allowed_att,home_ppda_allowed_def,home_rolling_xG_5,home_rolling_xGA_5,...,away_rolling_xG_5,away_rolling_xGA_5,away_rolling_npxGD_5,away_rolling_npxG_5,away_rolling_npxGA_5,away_rolling_xpts_5,away_rolling_deep_ratio_5,away_rolling_xG_std_5,away_rolling_xGA_std_5,away_rolling_npxGD_std_5
0,2025-08-15,Liverpool,Bournemouth,1,149,17,278,24,1.522302,1.716762,...,2.125290,2.152038,-0.026748,2.125290,2.152038,1.445775,0.5275,0.621273,1.570788,1.001281
1,2025-08-16,Brighton,Fulham,0,250,28,292,18,2.236066,1.185760,...,1.396540,1.692252,-0.295712,1.396540,1.692252,1.297625,0.3975,0.326041,1.001104,1.249884
2,2025-08-16,Sunderland,West Ham,1,291,14,165,15,1.059490,1.931333,...,1.326207,1.245384,0.080823,1.326207,1.245384,1.496175,0.6650,0.490030,1.064611,0.877820
3,2025-08-16,Tottenham,Burnley,1,108,17,295,17,1.195518,2.218155,...,1.722059,1.796850,0.115503,1.341477,1.225974,1.392450,0.4900,0.933009,1.150257,0.853362
4,2025-08-17,Chelsea,Crystal Palace,0,135,23,335,19,0.611685,2.494877,...,2.198205,1.910305,0.097608,2.007912,1.910305,1.633925,0.4200,0.230485,1.157434,1.483568

In [23]:
foot.seasons["2025"]

                                    ppda_att  ppda_def  ppda_allowed_att  \
team                    date
Arsenal                 2025-08-31       296        23               226
                        2025-09-13       219        20               291
                        2025-09-21       150        22               323
                        2025-09-28       145        20               247
                        2025-10-04       139        33               326
...                                      ...       ...               ...
Wolverhampton Wanderers 2025-12-30       296        17               207
                        2026-01-03       336        12               167
                        2026-01-07       200        19               245
                        2026-01-18       325        13               152
                        2026-01-24       371        18               231

                                    ppda_allowed_def  rolling_xG_5  \
team                    date
Arsenal                 2025-08-31                15      2.034005
                        2025-09-13                20      1.517896
                        2025-09-21                19      1.858847
                        2025-09-28                15      1.630793
                        2025-10-04                13      1.778809
...                                              ...           ...
Wolverhampton Wanderers 2025-12-30                27      0.791124
                        2026-01-03                32      0.829770
                        2026-01-07                24      1.225191
                        2026-01-18                20      1.243855
                        2026-01-24                39      1.068252

                                    rolling_xGA_5  rolling_npxGD_5  \
team                    date
Arsenal                 2025-08-31       0.766645         0.886775
                        2025-09-13       0.671565         0.592608
                        2025-09-21       0.577094         1.091461
                        2025-09-28       0.686215         0.792344
                        2025-10-04       0.558879         1.067695
...                                           ...              ...
Wolverhampton Wanderers 2025-12-30       1.983408        -1.192283
                        2026-01-03       1.985242        -1.155471
                        2026-01-07       1.222962        -0.302238
                        2026-01-18       1.226012        -0.286624
                        2026-01-24       1.076056        -0.160038

                                    rolling_npxG_5  rolling_npxGA_5  \
team                    date
Arsenal                 2025-08-31        1.653420         0.766645
                        2025-09-13        1.264173         0.671565
                        2025-09-21        1.668555         0.577094
                        2025-09-28        1.478559         0.686215
                        2025-10-04        1.626575         0.558879
...                                            ...              ...
Wolverhampton Wanderers 2025-12-30        0.638891         1.831174
                        2026-01-03        0.677537         1.833008
                        2026-01-07        0.920724         1.222962
                        2026-01-18        0.939388         1.226012
                        2026-01-24        0.916018         1.076056

                                    rolling_xpts_5  rolling_deep_ratio_5  \
team                    date
Arsenal                 2025-08-31        2.136250              0.565000
                        2025-09-13        1.847800              0.563333
                        2025-09-21        2.104275              0.650000
                        2025-09-28        1.869520              0.674000
                        2025-10-04        2.064720              0.766000
...                                            ...                   ...
Wolverhampton Wanderers 2025-12-30        0.740860              0.266000
                        2026-01-03        0.772260              0.330000
                        2026-01-07        1.331400              0.306000
                        2026-01-18        1.336560              0.408000
                        2026-01-24        1.287740              0.412000

                                    rolling_xG_std_5  rolling_xGA_std_5  \
team                    date
Arsenal                 2025-08-31          0.995048           0.862507
                        2025-09-13          1.137613           0.631728
                        2025-09-21          1.152287           0.549320
                        2025-09-28          1.120656           0.534651
                        2025-10-04          1.119935           0.383626
...                                              ...                ...
Wolverhampton Wanderers 2025-12-30          0.384502           1.170767
                        2026-01-03          0.421743           1.169090
                        2026-01-07          0.631292           0.585561
                        2026-01-18          0.609944           0.588167
                        2026-01-24          0.717992           0.576200

                                    rolling_npxGD_std_5
team                    date
Arsenal                 2025-08-31             1.319326
                        2025-09-13             1.062973
                        2025-09-21             1.322381
                        2025-09-28             1.326225
                        2025-10-04             1.249311
...                                                 ...
Wolverhampton Wanderers 2025-12-30             1.092210
                        2026-01-03             1.140302
                        2026-01-07             0.977292
                        2026-01-18             0.963930
                        2026-01-24             0.875095

[450 rows x 14 columns]